version: '3.8'

services:
  static:
    image: halverneus/static-file-server
    logging:
      driver: none
    environment:
      - PORT=3000
      - FOLDER=/app
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./app
        target: /app
  app_proxy:
    container_name: bigtest
    depends_on:
      - static
    image: caddy:alpine
    logging:
      driver: none
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: ./app-proxy/data
        target: /data
      - type: bind
        source: ./app-proxy/Caddyfile
        target: /etc/caddy/Caddyfile
  ws_proxy:
    container_name: websocket
    depends_on:
      - static
    image: caddy:alpine
    logging:
      driver: none
    ports:
      - "543:543"
    volumes:
      - type: bind
        source: ./ws-proxy/data
        target: /data
      - type: bind
        source: ./ws-proxy/Caddyfile
        target: /etc/caddy/Caddyfile
  manifest_proxy:
    container_name: manifest
    depends_on:
      - static
    image: caddy:alpine
    logging:
      driver: none
    ports:
      - "643:643"
    volumes:
      - type: bind
        source: ./manifest-proxy/data
        target: /data
      - type: bind
        source: ./manifest-proxy/Caddyfile
        target: /etc/caddy/Caddyfile
  chromedriver:
    depends_on:
      - app_proxy
      - ws_proxy
      - manifest_proxy
    image: pittst3r/chromedriver:latest
    logging:
      driver: none
    security_opt:
      - seccomp=unconfined
    ports:
      - "4567:4567"
      - "9222:9222"
  bigtest_server:
    container_name: server
    depends_on:
      - chromedriver
      - app_proxy
      - ws_proxy
      - manifest_proxy
      - static
    build:
      context: ./bigtest
    command: server
    ports:
      - "24001-24005:24001-24005"
    volumes:
      - type: bind
        source: ./bigtest/test
        target: /test
      - type: bind
        source: ./bigtest/node_modules
        target: /node_modules
      - type: bind
        source: ./bigtest/bigtest.json
        target: /bigtest.json
